services:
  xash3d:
    image: yohimik/cs-web-server-metpamx:latest
    build:
      context: ../../
      dockerfile: ./docker/cs-web-server-metpamx/Dockerfile
      tags:
        - yohimik/cs-web-server-metpamx:latest
        - yohimik/cs-web-server-metpamx:${TAG}
    restart: always
    platform: linux/386
    user: "0:0"
    environment:
      PORT: 27018
      IP: 192.168.50.123
    volumes:
      - "./cstrike:/xashds/cstrike"
      - "./valve.zip:/xashds/public/valve.zip"
    ports:
      - "27016:27016"
      - "27018:27018"
      - "27018:27018/udp"